AllCops:
  Exclude:
    - bin/**/*
    - script/**/*
    - vendor/**/*
    - cookbooks/**/*

ClassLength:
  Enabled: false
CyclomaticComplexity:
  Enabled: false
Documentation:
  Enabled: false
Encoding:
  Enabled: false
Layout/EmptyLinesAroundBlockBody:
  Enabled: true
Layout/ExtraSpacing:
  Enabled: true
  AllowForAlignment: false
  ForceEqualSignAlignment: false
Layout/SpaceBeforeFirstArg:
  Enabled: true
LineLength:
  Enabled: false
MethodLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/ModuleLength:
  Enabled: false
Naming/FileName:
  Enabled: true
PerceivedComplexity:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/RescueModifier:
  Enabled: true
Style/StringLiterals:
  Enabled: true
  Exclude: 'Gemfile'
Style/HashSyntax:
  Exclude: 'Gemfile'
Style/NumericLiterals:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false

# Offense count: 1
# Configuration parameters: Include.
# Include: **/*.gemspec
Gemspec/RequiredRubyVersion:
  Exclude:
    - 'ruby_http_client.gemspec'

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: AllowAliasSyntax, AllowedMethods.
# AllowedMethods: alias_method, public, protected, private
Layout/EmptyLinesAroundAttributeAccessor:
  Exclude:
    - 'lib/ruby_http_client.rb'

# Offense count: 1
Lint/MissingSuper:
  Exclude:
    - 'test/test_ruby_http_client.rb'

# Offense count: 1
# Cop supports --auto-correct.
Lint/RedundantCopDisableDirective:
  Exclude:
    - 'lib/ruby_http_client.rb'

# Offense count: 4
# Cop supports --auto-correct.
# Configuration parameters: Mode.
Style/StringConcatenation:
  Exclude:
    - 'lib/ruby_http_client.rb'
    - 'test/test_ruby_http_client.rb'
